services:
  flask_app:
    container_name: flask_app
    build:
      context: .
      dockerfile: backend/Dockerfile
    env_file:
      - .env
    depends_on:
      - flask_db
    networks:
      - shared_network
    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"
    volumes:
      - files:/app/files
    command: >
      python -m backend.app --db_username=postgres --db_host=flask_db --db_port=5432 --db_name=postgres --db_password=${DB_PASSWORD} --app_secret_key=${APP_SECRET_KEY} --app_host=${FLASK_HOST} --app_port=${FLASK_PORT}

  flask_db:
    container_name: flask_db
    image: postgres:12
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=postgres
    networks:
      - shared_network
    volumes:
      - db-data:/data

  flutter_app:
    container_name: flutter_app
    build:
      context: chabok_front
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - flask_app
    networks:
      - shared_network

networks:
  shared_network:
    driver: bridge

volumes:
  db-data:
  files:
