"""Auto-generated migration

Revision ID: 24789b232b91
Revises: 3e8d4a3fcd21
Create Date: 2025-01-02 15:29:59.347376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24789b232b91'
down_revision = '3e8d4a3fcd21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cookie_asd', sa.String(length=356), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cookie_asd')

    # ### end Alembic commands ###
