name: Backend Test Coverage

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  report-backend-test-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Run test coverage
        run: cd backend && coverage run -m pytest

      - name: Generate test coverage report
        run: cd backend && coverage report > backend_coverage_report.txt

      - name: Push coverage report
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add backend/backend_coverage_report.txt
          git commit -m "Add coverage report" || echo "No changes to commit"
          git push
