name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  backend_ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run tests
        run: |
          python -m unittest backend/**/*_test.py
          
  front_ci:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: chabok_front
        
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.0

      - name: Install dependencies
        run: flutter pub get
          
      - name: Build project
        run: |
          dart run build_runner build --delete-conflicting-outputs
          flutter create --platforms=web .
          flutter build web --base-href '/' --web-renderer canvaskit
          rm test/widget_test.dart

      - name: Run tests
        run: |
          flutter test test --dart-define=testing_mode=true
